# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84c15344018dd8d9d7c18582b0601c8d62af545eea205075ce76e62c5fadcf3dc674206380ea66bc5ffa59bcd2cd79a7069be75a864210b5e04468221aec0d1d

test:
  secret_key_base: 9870dabaee0052ecaead5dfb3080e33ee7e7179e289699b57903cfb8636c9a964cf35690967cd42c2417df6ee7617f5e4dd942379456f543b6078533db779288

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
